export const ADD_APPOINMENT = 'ADD_APPOINMENT';
export const REMOVE_APPOINMENT = 'REMOVE_APPOINMENT';

export const FETCH_PATIENT = 'FETCH_PATIENT';
export const FETCH_PATIENT_SUCCESS = 'FETCH_PATIENT_SUCCESS';
export const FETCH_PATIENT_FAILURE = 'FETCH_PATIENT_FAILURE';

export const DELETE_PATIENT = 'DELETE_PATIENT';
export const DELETE_PATIENT_FAILURE = 'DELETE_PATIENT_FAILURE';
export const DELETE_PATIENT_SUCCESS = 'DELETE_PATIENT_SUCCESS';

